# Week 2 Study Notebook

# UC San Diego OMDS DSC 207

In [2]:
# DO NOT MODIFY
%pip install otter-grader

Note: you may need to restart the kernel to use updated packages.


In [3]:
# Initialize Otter
import otter
grader = otter.Notebook()

In [4]:
# LOAD LIBRARIES
import numpy as np

### 1. Random array

Generate an integer random numpy array, `a`, of shape (3,5) with elements from 5 to 26 (inclusive). (Hint: Look at the documentation of `numpy.random.randint`) [1 pt]

For eg. 

    a = array([[26,  9, 24,  7, 15],
              [17, 15, 21, 18, 24],
              [ 5, 15, 10, 15, 13]])

In [5]:
# BEGIN SOLUTION NO PROMPT
a = np.random.randint(5,27,(3,5))
# END SOLUTION

""" # BEGIN PROMPT
a = ...
"""; # END PROMPT

In [6]:
assert a.shape == (3, 5)
assert np.max(a) <= 26

In [7]:
# HIDDEN
assert np.all(a >= 5)

In [8]:
# HIDDEN
assert np.all(a <= 26)

### 2. Transpose and inverse of the array `a`

1. The transpose of an array is created by using the first row of the array as the first column of the new array, the second row of the array as the second column of the new array, and so on. **Create transpose of array `a` using numpy.** Note - you should not write your own transpose function for this step. [0.5 pt]

For eg. The transpose of

    a = array([[26,  9, 24,  7, 15],
              [17, 15, 21, 18, 24],
              [ 5, 15, 10, 15, 13]])

    aT = array([[26, 17,  5],
                [ 9, 15, 15],
                [24, 21, 10],
                [ 7, 18, 15],
               [15, 24, 13]])

2. Like numbers, matrices do have reciprocals. In case of matrices, this reciprocal is called inverse matrix. If A is a square matrix and B is its inverse, then the product of two matrices is equal to the unit matrix. **Create the inverse of B using numpy.** (Hint: look up documentation for linalg library in numpy) [0.5 pt]

Initialize an integer numpy array `B`, of shape (2,2) as shown below. 
      
      B=array([[10,  6],
              [ 5,  5]])
       

In [9]:
a = np.array([[17, 20, 13, 23, 26],
              [21, 12,  9, 15,  6],
              [16, 23, 14, 25, 20]])

# BEGIN SOLUTION NO PROMPT
aT = np.transpose(a)
B = np.array([[10, 6],
              [5, 5]])
B_inv = np.linalg.inv(B)
# END SOLUTION

""" # BEGIN PROMPT
aT = ...
B = ...
B_inv = ...
"""; # END PROMPT

In [10]:
assert aT.shape == (5, 3)
assert np.min(aT) >= 5
assert np.linalg.det(B_inv) != 0

In [11]:
# HIDDEN
for i in range(5):
    for j in range(3):
        assert aT[i, j] == a[j, i]

In [12]:
# HIDDEN
answer = np.array([[ 0.25, -0.3 ],
                   [-0.25,  0.5 ]])

np.testing.assert_allclose(B_inv, answer)

### 3. Array slicing
1. Slicing in python means taking elements from one given index to another given index. **Retrieve elements from last 2 rows and last 2 columns of array `a` and store the result in `c`** [0.5 pt]

For eg. for the above array A - the last 2 columns and last 2 rows are

    array([[18, 24],
            [15, 13]])

2. Retrieve the 2nd and 3rd rows of array `a` from the first question and store the result in `d`.  [0.5 pt]

For eg. for the above array A, the 2nd and 3rd rows are

      array([[17, 15, 21, 18, 24],
            [ 5, 15, 10, 15, 13]])

In [13]:
# BEGIN SOLUTION NO PROMPT
c = a[1:, -2:]
d = a[1:,]
# END SOLUTION

""" # BEGIN PROMPT
c = ...
d = ...
"""  # END PROMPT

' # BEGIN PROMPT\nc = ...\nd = ...\n'

In [14]:
assert c.shape == (2, 2)

assert d.shape == (2, 5)

In [15]:
# HIDDEN
answer1 = np.array([[15,  6],
                    [25, 20]])

answer2 = np.array([[21, 12,  9, 15,  6],
                   [16, 23, 14, 25, 20]])

np.testing.assert_equal(d, answer2) and np.testing.assert_equal(c, answer1)

### 4. Broadcasting

1. Broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Below you can see the difference between vector addition for traditional lists and numpy arrays.




In [16]:
# If we were not using numpy arrays, we would have to loop through the array. Run this cell.
arr= [[27, 11, 27, 11, 20],
       [18, 17, 24, 22, 29],
       [ 6, 17, 13, 19, 18]]
c = [1,2,3,4,5]
for row in range(len(arr)):
  for col in range(len(arr[0])):
    arr[row][col] = arr[row][col]+c[col]
arr

[[28, 13, 30, 15, 25], [19, 19, 27, 26, 34], [7, 19, 16, 23, 23]]


**Create a vector `c=[1,2,3,4,5]`. Add this vector to array `a` using numpy broadcasting. Store the result in `x`.**  [0.5 pt]

For eg. for the array A - the result array would be

    array([[27, 11, 27, 11, 20],
          [18, 17, 24, 22, 29],
          [ 6, 17, 13, 19, 18]])

2. **(True / False) Is it possible to add array b to a? Explain why?**  [0.5 pt]

In [17]:
# BEGIN SOLUTION NO PROMPT
c = [1, 2, 3, 4, 5]
x = a + c
# END SOLUTION

""" # BEGIN PROMPT
c = ...
x = ...
"""  # END PROMPT

' # BEGIN PROMPT\nc = ...\nx = ...\n'

In [18]:
assert x.shape == (3, 5)

assert np.array_equal(x, a) == False

### 5. Reshaping

**Create a list `B=[1,2,3]` and add it to all the columns of `a`. Store the resulting array in z** (Hint: Use reshape and broadcasting)  [1 pt]

For eg. for the modified array A, the result would be

    array([[27, 10, 25,  8, 16],
          [19, 17, 23, 20, 26],
          [ 8, 18, 13, 18, 16]])

In [19]:
# BEGIN SOLUTION NO PROMPT
B = [1, 2, 3]
B_reshape = np.reshape(B, (3, 1))
z = a + B_reshape
# END SOLUTION

""" # BEGIN PROMPT
B = ...
z = ...
"""  # END PROMPT

' # BEGIN PROMPT\nB = ...\nz = ...\n'

In [20]:
assert z.shape == (3, 5)

assert np.array_equal(z, a) == False

In [21]:
# HIDDEN
expected_z = np.array([[18, 21, 14, 24, 27],
                       [23, 14, 11, 17,  8],
                       [19, 26, 17, 28, 23]])

np.testing.assert_equal(z, expected_z)

### 6. Data analysis using numpy

**Normalization: Create a new array where each element in `a` is adjusted by subtracting the mean of its corresponding row. Store this new array in a_norm.** (Hint: look at numpy's mean method and it's arguments) [2 pt]

For eg. for the modified array A, the expected output would be

    array([[ 9.8, -7.2,  7.8, -9.2, -1.2],
          [-2. , -4. ,  2. , -1. ,  5. ],
          [-6.6,  3.4, -1.6,  3.4,  1.4]])

In [22]:
# BEGIN SOLUTION NO PROMPT
a_norm = a - a.mean(axis=1, keepdims=True)
# END SOLUTION

""" # BEGIN PROMPT
a_norm = ...
"""  # END PROMPT

' # BEGIN PROMPT\na_norm = ...\n'

In [23]:
assert a_norm.shape == (3, 5)

In [24]:
# HIDDEN
answer = np.array([[-2.8,  0.2, -6.8,  3.2,  6.2],
                   [ 8.4, -0.6, -3.6,  2.4, -6.6],
                   [-3.6,  3.4, -5.6,  5.4,  0.4]])

np.testing.assert_allclose(answer, a_norm)

### 7. Data manipulation in numpy arrays.

**Swap first and second row of array `a`. Store the new array in X.** [0.5 pt]

For eg. for the modified array `a` the expected output would be

    array([[17, 15, 21, 18, 24],
           [26,  9, 24,  7, 15],
           [ 5, 15, 10, 15, 13]])

**Swap second and third column of array `X`. Store the new array in `Y`.**  [0.5 pt]

For eg. for the modified array `a` the expected output would be
   
    array([[17, 15, 21, 18, 24],
           [ 5, 15, 10, 15, 13],
           [26,  9, 24,  7, 15]])

In [25]:
# BEGIN SOLUTION NO PROMPT
X = a.copy()
X[[0,1]]=X[[1,0]]

Y = X.copy()
Y[[1,2]]=Y[[2,1]]
# END SOLUTION

""" # BEGIN PROMPT
X = ...
Y = ...
"""  # END PROMPT

' # BEGIN PROMPT\nX = ...\nY = ...\n'

In [26]:
assert X.shape == (3, 5)

assert Y.shape == (3, 5)

In [27]:
# HIDDEN
assert np.array_equal(a[0], X[1]) and np.array_equal(a[1], X[0])

In [28]:
# HIDDEN
assert np.array_equal(X[1], Y[2]) and np.array_equal(X[2], Y[1])

### The Power Of Numpy

In [29]:
#Run this cell
import time

twoD_list = [[i for i in range(500)] for j in range(500)]

# This a traditional matrix multiplication using for loops
def matrix_multiplication(x, y):
    dp = 0
    prod=[]
    for i in range(len(x)):
      row=[]
      for j in range(len(x[0])):
        mul=0
        for k in range(len(x[0])):
          mul += (x[i][k]*y[k][j])
        row.append(mul)
      prod.append(row)

    return prod

In [30]:
# Run this cell. Note the time taken to perform traditional matrix multiplication using lists.
start_time = time.time()
dot_product_list = matrix_multiplication(twoD_list, twoD_list)
end_time = time.time()
print(end_time-start_time)

5.337973117828369


**Convert the `twoD_list` to a numpy array `numpy_twoD_array`. Print the numpy array**

For eg.

    numpy_twoD = array([[  0,   1,   2, ..., 497, 498, 499],
                        [  0,   1,   2, ..., 497, 498, 499],
                        [  0,   1,   2, ..., 497, 498, 499],
                         ...,
                        [  0,   1,   2, ..., 497, 498, 499],
                        [  0,   1,   2, ..., 497, 498, 499],
                        [  0,   1,   2, ..., 497, 498, 499]])

**Perform matrix multiplication of the numpy array i.e. numpy_twoD_array * numpy_twoD_array. Record the result in dot_product_array and report the time taken for the operation similar to traditional list multiplication.**  [2 pt]

In [31]:
start_time=time.time();

dot_product_array = ...

# BEGIN SOLUTION NO PROMPT
numpy_twoD_array = np.array(twoD_list)
dot_product_array = np.matmul(numpy_twoD_array, numpy_twoD_array)
# END SOLUTION

end_time=time.time();
print(end_time-start_time)

0.07144880294799805


In [33]:
assert dot_product_array.shape == (500, 500)

In [34]:
# HIDDEN
assert np.array_equal(dot_product_array, dot_product_list)

### Submission

Before you submit your notebook, ensure that you've run all the cells sequentially to display images, graphs, and outputs correctly. Take the time to review your solutions and evaluate using the public test cases. Once you're satisfied, save your notebook by navigating to "File" in the Jupyter Notebook menu and selecting "Save" or using the keyboard shortcut (usually Ctrl + S or Cmd + S).

To submit, export your notebook as an .ipynb file. Ensure it's saved with the same name as the assignment. Then, upload this .ipynb file to Gradescope. Remember to submit the correct version.

Please save your work before exporting it, and if you encounter any technical issues or have questions about the submission process, reach out to the course staff for assistance