## Instructions


*   You can complete the assignment in Jupyter/Colab
*   If you are using Colab, make a copy of the notebook in your own drive
*   To make a submission -
  *  Download the source ipynb file
  *  Upload to gradescope






### 0. Import Numpy


In [ ]:
import numpy as np

### 1. Random array

Generate an integer random numpy array, A, of shape (3,5) with elements from 5 to 26(inclusive). Print the generated random array. (Hint: Look at the documentation of `numpy.random.randint`) [1 pt]

In [ ]:
#a = np.random.randint(low=5,high=27,size=(3,5))
a = np.random.randint(5,27,(3,5))
a

array([[26,  7, 15, 22, 14],
       [ 6, 15,  5, 25, 15],
       [21, 18, 21, 22,  9]])

### 2. Transpose and inverse of the array `A`

1. The transpose of an array is created by using the first row of the array as the first column of the new array, the second row of the array as the second column of the new array, and so on. **Print the transpose of A using numpy.** Note - you should not write your own transpose function for this step. [0.5 pt]

For eg. The transpose of

    x = array([[26,  9, 24,  7, 15],
              [17, 15, 21, 18, 24],
              [ 5, 15, 10, 15, 13]])

    xT = array([[26, 17,  5],
                [ 9, 15, 15],
                [24, 21, 10],
                [ 7, 18, 15],
               [15, 24, 13]])

In [ ]:
np.transpose(a)

array([[26,  6, 21],
       [ 7, 15, 18],
       [15,  5, 21],
       [22, 25, 22],
       [14, 15,  9]])

2. Generate a integer random numpy array B, of shape (2,2) with elements from 5 to 12(inclusive). Print B.

In [ ]:
b = np.random.randint(5,13,(2,2))
b

array([[ 7, 10],
       [ 6,  8]])

Like numbers, matrices do have reciprocals. In case of matrices, this reciprocal is called inverse matrix. If A is a square matrix and B is its inverse, then the product of two matrices is equal to the unit matrix. **Print the inverse of B using numpy.** (Hint: look up documentation for linalg library in numpy) [0.5 pt]

For eg.
      
      Inverse of
      x=array([[10,  6],
              [ 5,  5]])
       
      x_inv=array([[ 0.25, -0.3 ],
                  [-0.25,  0.5 ]])


In [ ]:
np.linalg.inv(b)

array([[-2.  ,  2.5 ],
       [ 1.5 , -1.75]])

### 3. Array slicing
1. Slicing in python means taking elements from one given index to another given index. **Print the last 2 columns of array A.** [0.5 pt]

For eg. for the above array A - the last 2 columns are

    array([[ 7, 15],
            [18, 24],
            [15, 13]])

In [ ]:
#a[:,-2:]
a[0:3, 3:5]

array([[22, 14],
       [25, 15],
       [22,  9]])

2. Print the 2nd and 3rd rows of array A.  [0.5 pt]

For eg. for the above array A, the 2nd and 3rd rows are

      array([[17, 15, 21, 18, 24],
            [ 5, 15, 10, 15, 13]])

In [ ]:
# a[1:3,:]
a[1:,]

array([[ 6, 15,  5, 25, 15],
       [21, 18, 21, 22,  9]])

### 4. Broadcasting

1. Broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Below you can see the difference between vector addition for traditional lists and numpy arrays.




In [ ]:
# If we were not using numpy arrays, we would have to loop through the array -
arr= [[27, 11, 27, 11, 20],
       [18, 17, 24, 22, 29],
       [ 6, 17, 13, 19, 18]]
c = [1, 2, 3, 4, 5]
for row in range(len(arr)):
  for col in range(len(arr[0])):
    arr[row][col] = arr[row][col]+c[col]
arr

NameError: ignored


**Create a vector `c=[1,2,3,4,5]`. Add this vector to array `a` using numpy broadcasting. Print the result.**  [0.5 pt]

For eg. for the array A - the result array would be

    array([[27, 11, 27, 11, 20],
          [18, 17, 24, 22, 29],
          [ 6, 17, 13, 19, 18]])



In [ ]:
c=[1,2,3,4,5]
a=a+c
a

array([[27,  9, 18, 26, 19],
       [ 7, 17,  8, 29, 20],
       [22, 20, 24, 26, 14]])

2. **(True / False) Is it possible to add vector b to a? Explain why?**  [0.5 pt]

No, as a is of shape (3,5) and b is of shape(2,2) and hence they are not compatible for broadcasting

In [ ]:
import numpy as np
a=np.array([[27, 11, 27, 11, 20],
       [18, 17, 24, 22, 29],
       [ 6, 17, 13, 19, 18]])

### 5. Reshaping

**Create a list `B=[1,2,3]` and add it to all the columns of `a`. Print the resulting array** (Hint: Use reshape and broadcasting)  [1 pt]

For eg. for the modified array A, the result would be

    array([[28, 12, 28, 12, 21],
          [20, 19, 26, 24, 31],
          [ 9, 20, 16, 22, 21]])

In [ ]:
# Reshape b using np.reshape
B=[1,2,3]
b_reshape=np.reshape(B,(3,1))
a=a+b_reshape
a

array([[28, 12, 28, 12, 21],
       [20, 19, 26, 24, 31],
       [ 9, 20, 16, 22, 21]])

### 6. Data analysis using numpy

**Normalization: Substract mean from each row of array `a`. Print the result array.**. (Hint: look at numpy's mean method and it's arguments) [2 pt]

For eg. for the modified array A, the expected output would be

    array([[ 7.8, -8.2,  7.8, -8.2,  0.8],
          [-4. , -5. ,  2. ,  0. ,  7. ],
          [-8.6,  2.4, -1.6,  4.4,  3.4]])

In [ ]:
mean = np.array([np.mean(row) for row in a])
mean

array([20.2, 24. , 17.6])

In [ ]:
np.mean(a)

20.6

In [ ]:
mean=mean.reshape(3,1)
sub_mean=a-mean
sub_mean

array([[ 7.8, -8.2,  7.8, -8.2,  0.8],
       [-4. , -5. ,  2. ,  0. ,  7. ],
       [-8.6,  2.4, -1.6,  4.4,  3.4]])

In [ ]:
Y = a - a.mean(axis=1, keepdims=True)
Y

array([[ 7.8, -8.2,  7.8, -8.2,  0.8],
       [-4. , -5. ,  2. ,  0. ,  7. ],
       [-8.6,  2.4, -1.6,  4.4,  3.4]])

### 7. Data manipulation in numpy arrays.

**Swap first and second row of array `a`. Print the result array.** [0.5 pt]

For eg. for the modified array `a` the expected output would be

    array([[20, 19, 26, 24, 31],
          [28, 12, 28, 12, 21],
          [ 9, 20, 16, 22, 21]])


In [ ]:
print(a)
a[[0,1]]=a[[1,0]]
a

[[28 28 12 12 21]
 [20 26 19 24 31]
 [ 9 16 20 22 21]]


array([[20, 26, 19, 24, 31],
       [28, 28, 12, 12, 21],
       [ 9, 16, 20, 22, 21]])

**Swap second and third column of array `a`. Print the result array.**  [0.5 pt]

For eg. for the modified array `a` the expected output would be
   
    array([[20, 26, 19, 24, 31],
          [28, 28, 12, 12, 21],
          [ 9, 16, 20, 22, 21]])

In [ ]:
a[:,[1,2]]=a[:,[2,1]]
a

array([[28, 12, 28, 12, 21],
       [28, 12, 28, 12, 21],
       [ 9, 20, 16, 22, 21]])

### The Power Of Numpy

In [ ]:
#Run this cell
import time

In [ ]:
#Run this cell
twoD_list = [[i for i in range(500)] for j in range(500)]

In [ ]:
#Run this cell
#This a traditional matrix multiplication using for loops
def matrix_multiplication(x, y):
    dp = 0
    prod=[]
    for i in range(len(x)):
      row=[]
      for j in range(len(x[0])):
        mul=0
        for k in range(len(x[0])):
          mul += (x[i][k]*y[k][j])
        row.append(mul)
      prod.append(row)

    return prod

In [ ]:
#Run this cell. Note the time taken to perform traditional matrix multiplication using lists.
start_time=time.time()
dot_product_list = matrix_multiplication(twoD_list, twoD_list)
end_time=time.time()
print(end_time-start_time)

KeyboardInterrupt: ignored

**Convert twoD_list to a numpy array `numpy_twoD_array`. Print the numpy array**

For eg.

    numpy_twoD = array([[  0,   1,   2, ..., 497, 498, 499],
                        [  0,   1,   2, ..., 497, 498, 499],
                        [  0,   1,   2, ..., 497, 498, 499],
                         ...,
                        [  0,   1,   2, ..., 497, 498, 499],
                        [  0,   1,   2, ..., 497, 498, 499],
                        [  0,   1,   2, ..., 497, 498, 499]])

In [ ]:
#ToDo
nump_arr=np.array(twoD_list)
nump_arr

**Perform matrix multiplication of the numpy array i.e. numpy_twoD_array * numpy_twoD_array. Record and report the time taken for the operation similar to traditional list multiplication.**  [2 pt]



In [ ]:
start_time=time.time();
## Insert dot product of num_arr with itself
numpy_dot_product = np.dot(nump_arr,nump_arr)
end_time=time.time();
print(end_time-start_time)
print(numpy_dot_product)

In [ ]:
np.multiply(nump_arr, nump_arr)

In [ ]:
nump_arr ** 2

In [ ]:
a

In [ ]:
a[:-1]